### ISSUE TITLE
Help me host it?

### ISSUE THREAD

**Issue by RetroGameTalk** [kotcrab/xdelta-wasm#2]
![Capture](https://github.com/kotcrab/xdelta-wasm/assets/8179611/eb819e18-fa77-4167-b83c-8e090b16110b)

Hello, i managed to build and got the public folder but when trying o host it it's just a blank screen with no errors.

````
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta name="description" content="Online xdelta and xdelta3 patcher" />
    <link rel="apple-touch-icon" href="logo192.png" />
    <link rel="manifest" href="manifest.json" />
    <title>Xdelta patcher</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
  </body>
</html>
```

**Comment by kotcrab** [comment]
Already build code is on the [gh-pages](https://github.com/kotcrab/xdelta-wasm/tree/gh-pages) branch, compare against that. You are missing the `static/js` folder and the `inedx.html` doesn't look like it was processed so most likely you didn't run `npm run build`.

**Comment by RetroGameTalk** [comment]
> Already build code is on the [gh-pages](https://github.com/kotcrab/xdelta-wasm/tree/gh-pages) branch, compare against that. You are missing the `static/js` folder and the `inedx.html` doesn't look like it was processed so most likely you didn't run `npm run build`.

That works! Is there any way to separate the actual tool from the css colors it changes and the dark mode functionality?

**Comment by kotcrab** [comment]
See [PatchForm.js](https://github.com/kotcrab/xdelta-wasm/blob/6b4eb0db09e7fd34fdb9f51dba9d0bcd65a826a7/src/PatchForm.js) for how to use the xdelta worker and write your code based on that.

**Comment by sergeevabc** [comment]
Does not work on my end.
```
Error occurred while patching
Details: unavailable secondary compressor: LZMA (code -17710)
```
Patch was created by [xdelta 3.1.0 beta](https://github.com/jmacd/xdelta-gpl).

**Comment by kotcrab** [comment]
I created new issue as your comment is not relevant to this issue.
