### ISSUE TITLE
New secondary compressor: LZMA

### ISSUE THREAD

**Issue by kotcrab** [kotcrab/xdelta-wasm#3]
Does not work on my end.
```
Error occurred while patching
Details: unavailable secondary compressor: LZMA (code -17710)
```
Patch was created by [xdelta 3.1.0 beta](https://github.com/jmacd/xdelta-gpl).

_Originally posted by @sergeevabc in https://github.com/kotcrab/xdelta-wasm/issues/2#issuecomment-1918317181_

**Comment by kotcrab** [comment]
LZMA is a new secondary compressor that xdelta needs to be recompiled with.

**Comment by sergeevabc** [comment]
Is it possible to do?

**Comment by kotcrab** [comment]
It should be doable.

**Comment by sergeevabc** [comment]
I confirm that it works as expected.
Thank you for not taking too long, @kotcrab.
