### ISSUE TITLE
Patcher not working

### ISSUE THREAD

**Issue by GamingNinjaYT1** [kotcrab/xdelta-wasm#4]
Sir I'm on Android and when I try to patch a pokemon game moon black 2 whenever I try to patch game it shows it is trying to patch but it didn't patch the game I let it sit for on hour to patch but it didn't pls help me with this issue

**Comment by kotcrab** [comment]
What patch exactly you're trying to apply? What browser you're using and what version? Have you tried different browsers?
Unfortunately unless you can provide [errors logs](https://stackoverflow.com/questions/37256331/is-it-possible-to-open-developer-tools-console-in-chrome-on-android-phone) we're unlikely to figure out what's wrong.

**Comment by kotcrab** [comment]
Closing, not enough details to reproduce.
